"""Grazer cycle strength per sweep cell, for SWEEP_FINDINGS.md.

usage: python sweeps/cycle_ratio.py sweeps/<name> [from_tick]

Reads sweeps/<name>/sweep.csv and cells/*.csv (cells are regenerated by rerunning the sweep).
Smoothing and local maxima replicate check.rs exactly: 200-tick centred moving average
(window [t-100, t+99]); a maximum is >= every smoothed value within +-500 ticks and strictly
greater than at least one; plateaus collapse to their first tick. As a cross-check, the
maxima count from tick 2000 must equal sweep.csv's grazer_peaks column.

For each maximum after `from_tick` (default 4000), its trough is the smoothed minimum between
the previous maximum (or from_tick for the first) and the peak; ratio = peak / trough.
A peak "qualifies" when ratio >= 1.5. `hunters@peaks` lists the raw hunter count at each qualifying
peak tick (older sweeps without a hunters column print '-').
"""
import csv
import os
import statistics
import sys


def moving_average(v, w=200):
    half = w // 2
    prefix = [0.0]
    for x in v:
        prefix.append(prefix[-1] + x)
    return [None if t < half or t + (w - half) > len(v) else (prefix[t + w - half] - prefix[t - half]) / w
            for t in range(len(v))]


def maxima(ma, frm, to):
    out = []
    for t in range(frm, min(to, len(ma) - 1) + 1):
        v = ma[t]
        if v is None:
            continue
        lo, hi = max(t - 500, 0), min(t + 500, len(ma) - 1)
        ok, strictly = True, False
        for s in range(lo, hi + 1):
            if s == t or ma[s] is None:
                continue
            if ma[s] > v:
                ok = False
                break
            if v > ma[s]:
                strictly = True
        if ok and strictly:
            if out and ma[out[-1]] == v and all(ma[s] == v for s in range(out[-1] + 1, t)):
                continue
            out.append(t)
    return out


def cycle_stats(grazers, frm):
    ma = moving_average(grazers)
    last = len(grazers) - 1
    peaks = maxima(ma, frm, last)
    ratios = []
    prev = frm
    for p in peaks:
        trough = min(x for x in ma[prev:p + 1] if x is not None)
        ratios.append(ma[p] / trough if trough > 0 else float('inf'))
        prev = p
    return ma, peaks, ratios


def main():
    d = sys.argv[1]
    frm = int(sys.argv[2]) if len(sys.argv) > 2 else 4000
    rows = list(csv.DictReader(open(os.path.join(d, 'sweep.csv'))))
    params = [k for k in rows[0] if k != 'seed' and not k.endswith(('_pass', '_value', '_margin'))
              and k not in ('first_extinction_tick', 'first_extinction_species', 'first_extinction_dominant_cause',
                            'grazer_peaks', 'hunter_extinction_tick', 'hunter_immigrants',
                            'pp_lag', 'pp_corr', 'pp_undefined', 'pp_period', 'pp_pass')]
    print(f"{' '.join(params)} seed | peaks>{frm} qualifying(>=1.5) | ratio min/median/max | answer | hunters@peaks")
    for r in rows:
        cid = '_'.join(f'{p}={r[p]}' for p in params) + f"_s={r['seed']}"
        cell = list(csv.DictReader(open(os.path.join(d, 'cells', cid + '.csv'))))
        g = [float(x['grazers']) for x in cell]
        ma, _, _ = cycle_stats(g, frm)
        assert len(maxima(ma, 2000, len(g) - 1)) == int(r['grazer_peaks']), f'{cid}: peak count mismatch'
        _, peaks, ratios = cycle_stats(g, frm)
        q = sum(x >= 1.5 for x in ratios)
        rs = f'{min(ratios):.2f}/{statistics.median(ratios):.2f}/{max(ratios):.2f}' if ratios else '-'
        hp = ','.join(cell[p]['hunters'] for p, x in zip(peaks, ratios) if x >= 1.5) if 'hunters' in cell[0] else '-'
        print(f"{' '.join(r[p] for p in params)} s{r['seed']} | {len(peaks)} {q} | {rs} | {'YES' if q >= 2 else 'NO'} | {hp or '-'}")


if __name__ == '__main__':
    main()
